#!/bin/sh
cat <<EOT
Welcome $USER, you have successfully logged in!

Please use git clone/push/pull to access your repo(s).
In addition, you may use the following commands:
		(git-shell suite ver.18-12-17)

* help  : this help
* stat  : display system status and disk usage of home directory
* tidy  : search for '.git' and do 'git gc' and 'git fsck' there
* keys  : add or delete public ssh keys (don't remove all of them!)
* read  : read messages from system admin (end with 'q')
* write : send message to system admin
* schat : simple local shell chat (if installed)
* repos : list/add/delete additional git repositories
* mango : manage gopherhole: reinitialize to state after account creation
          or prepare for pushing remote repository content
          (Warning: destroys all existing content in gopherhole!)
* quit or exit : close this shell

Please note: message exchange with sysadmin may be slow -- patience!

EOT
