#!/bin/sh
# directory for additional repositories
rd=r
# max.length of repo names
rnmlen=12

# function for listing repos and (if arg=sel) returning name
listrd() {
 local rl
# numbered directory, squeeze white space to single space
 rl="`ls -1|nl|sed -e 's/[ 	][ 	]*/ /g'`"
 echo "$rl" >&2
 if test "$1" = "sel"
 then
  echo ' which?' >&2
  read ind
# sanitize input to number only
  ind=`echo "$ind" | tr -c -d 0-9`
# search for line number, filter out directory name
  echo "$rl" | grep "^ *${ind} " | sed -e 's/ *[1-9][0-9]* //'
 fi
}

# make sure repo directory exists
if test ! -d $rd
then mkdir $rd
 echo "(new $rd directory created)"
fi
# with all read and execute permissions
chmod 755 $rd
# and go there
cd $rd

echo repositories:
listrd
cat <<EOH

Please enter 'add' to add a new repository (.git will be appended),
or 'del' to select a repository for deletion:
EOH
read cmd
case $cmd in
add) echo "name of new repo (up to $rnmlen letters and numbers):"
 read rena
# sanitize input to letters and numbers only
 rena=`echo "$rena" | tr -c -d 0-9A-Za-z`
# and check for length
 if test ${#rena} -ge 2 -a ${#rena} -le $rnmlen
# add suffix and check whether exists
 then rena=$rena.git
  if test ! -d $rena
  then echo "installing new (bare, accessible) git repo $rena"
   mkdir $rena
   chmod 3755 $rena
   git init --bare $rena
   touch $rena/git-daemon-export-ok
  else echo "repo $rena already exists!"
  fi
  cat <<EOH
 repo can be cloned/pushed as HOSTNAME:$rd/$rena
 where HOSTNAME is your ssh definition for accessing your account
EOH
 else echo "'$rena' is too short or longer than $rnmlen, not created!"
 fi
 ;;
del) echo 'Please enter number of repo to delete:'
 rena=`listrd sel`
 if test "$rena" != ""
 then
  echo "Please confirm with ok to delete repo '$rena'!"
  read cmd
  if test "$cmd" = "ok" -o "$cmd" = "OK"
  then rm -rf $rena
   echo "'$rena' is deleted"
  else echo "'$rena' is kept"
  fi
 else echo nothing selected
 fi
 ;;
*) echo 'unrecognized command ignored'
 ;;
esac

cat <<EOT

repositories now present:
EOT
listrd
echo
