#!/bin/sh
rc=.schatnrc
gd=$HOME/public_gopher

if test "`command -v schat`" = ""
then echo 'sorry, schat does not seem to be available!'
 exit
fi
schat

if ! test -h $rc
then echo :: moving schat config ...
 cat $rc > $gd/$rc
 /bin/rm -f $rc
 ln -s $gd/$rc $rc
 cd $gd
 git add $rc
 git commit -m "(automatically adding $rc)"
 git push origin master
 echo :: done. you may now edit $rc in your gopher repository
fi
