#!/bin/sh
cat <<EOT
Welcome $USER, you have successfully logged in!
However, this system does not provide interactive access, sorry.
Please use git-push and git-pull only.
(closing connection at `date`)
EOT
exit 128
