#!/bin/sh
cat <<EOT
Welcome $USER, you have successfully logged in!

Please use git clone/push/pull to access your repo(s).
In addition, you may use the following commands:
		(git-shell suite ver.19-01-23)

* help  : this help
* stat  : display system status and disk usage of home directory
* tidy  : search for '.git' and do 'git gc' and 'git fsck' there,
          then reinstall gopher directory from its git repository
* repos : list/add/delete additional git repositories
* quit or exit : close this shell

EOT
